#Minecraft server properties
#Thu Apr 03 01:16:56 EDT 2025
server-name=Minecraft Server
motd=Welcome to my Minecraft Server\!
public=false
port=25565
verify-names=false
max-players=16
max-connections=16
